# Grupo em minúscula!!
Vip_grupos:
  - vip
  - vip+
  - pro
  - noob
Comandos_trocar:
  - 'pex user %name% group remove %oldgroup%'
  - 'pex user %name% group add %newgroup%'
Comandos_remover:
  - 'pex user %name% group remove %grupo%'
  - 'pex user %name% group add Membro'
Comandos_ativacao:
  - 'vip,pex user %name% group add vip'
  - 'vip+,pex user %name% group add vip+'
  - 'pro,pex user %name% group add pro'
  - 'noob,pex user %name% group add noob'